### ISSUE TITLE
protectedHeader should be wrapped in a bstr

### ISSUE THREAD

**Issue by qmuntal** [gluecose/test-vectors#9]
https://datatracker.ietf.org/doc/html/rfc8152#section-3 defines the protected header as a map wrapped in a bstr, but test-vectors represent it as just a map.

**Comment by thomas-fossati** [comment]
We chose to use the unwrapped map for `protectedHeader` to balance presentation & ease of use.  The expectation is that this is a format that can be easily consumed by the implementation that needs to populate the internal representation of the TBS, while at the same time remaining "readable" by the user.

**Comment by qmuntal** [comment]
Legit. Closing the issue then.
